-- ============================================================
-- FPMED — DDL do banco (derivado do uso real no codigo do app)
-- Seguro re-rodar: tudo com IF NOT EXISTS. Sem DROP/DELETE.
-- RLS fica OFF (igual ao GlobalMed hoje); "expose new tables" ON => grants automaticos.
-- ============================================================

-- FORNECEDORES
create table if not exists public.fornecedores (
  id         bigint generated always as identity primary key,
  nome       text,
  cnpj       text,
  tipo       text,
  contato    text,
  telefone   text,
  created_at timestamptz default now()
);

-- COTACOES (coracao: produtos/precos)
create table if not exists public.cotacoes (
  id                     bigint generated always as identity primary key,
  fornecedor             text,
  fornecedor_nome        text,
  tipo                   text,
  pedido                 text,
  data                   date,
  codigo                 text,
  produto                text,
  principio_ativo        text,
  und                    text,
  vencimento             date,
  marca                  text,
  compra_unit            numeric,
  compra_caixa           numeric,
  qtd_orcamento          numeric,
  total_compra           numeric,
  estoque                numeric,
  global_venda1          numeric,
  global_venda2          numeric,
  markup                 numeric,
  regra                  text,
  venda_unit_calculada   numeric,
  venda_caixa_calculada  numeric,
  total_venda_calculado  numeric,
  venda_loja             numeric,
  created_at             timestamptz default now()
);

-- CLIENTES (cnpj_normalizado GERADA + unique; codigo identity unico p/ FK)
create table if not exists public.clientes (
  id                bigint generated always as identity primary key,
  codigo            bigint generated by default as identity,
  nome              text,
  cnpj              text,
  cnpj_normalizado  text generated always as (regexp_replace(coalesce(cnpj,''), '\D', '', 'g')) stored,
  cod_cliente_erp   text,
  vendedora         text,
  contato           text,
  whatsapp          text,
  email             text,
  cidade            text,
  uf                text,
  obs               text,
  criado_em         timestamptz default now(),
  atualizado_em     timestamptz default now()
);
do $$ begin
  if not exists (select 1 from pg_constraint where conname='clientes_codigo_key') then
    alter table public.clientes add constraint clientes_codigo_key unique (codigo);
  end if;
  if not exists (select 1 from pg_constraint where conname='clientes_cnpjnorm_key') then
    alter table public.clientes add constraint clientes_cnpjnorm_key unique (cnpj_normalizado);
  end if;
  if not exists (select 1 from pg_constraint where conname='clientes_coderp_key') then
    alter table public.clientes add constraint clientes_coderp_key unique (cod_cliente_erp);
  end if;
end $$;

-- COMPRAS (cabecalho; cliente_codigo -> clientes.codigo p/ embed PostgREST)
create table if not exists public.compras (
  id            bigint generated always as identity primary key,
  cliente_codigo bigint references public.clientes(codigo),
  cliente_nome  text,
  numero_pedido text,
  valor_total   numeric,
  data_compra   date,
  vendedor_nome text,
  origem        text,
  created_at    timestamptz default now()
);

-- COMPRA_ITENS (compra_id -> compras.id p/ embed compras!inner)
create table if not exists public.compra_itens (
  id           bigint generated always as identity primary key,
  compra_id    bigint references public.compras(id),
  codigo_erp   text,
  produto      text,
  produto_norm text,
  principio_ativo text,
  marca        text,
  und          text,
  quantidade   numeric,
  preco_unit   numeric,
  preco_caixa  numeric,
  total_item   numeric
);

-- ORCAMENTOS (itens em JSON)
create table if not exists public.orcamentos (
  id               bigint generated always as identity primary key,
  numero           text,
  numero_orcamento text,
  cliente          text,
  cnpj_cliente     text,
  cliente_id       bigint,
  condicao         text,
  vendedora        text,
  validade         date,
  desconto_geral   numeric,
  itens            jsonb,
  status           text,
  total_geral      numeric,
  criado_em        timestamptz default now(),
  atualizado_em    timestamptz default now()
);

-- ITENS_A_COTAR (fila de faltantes)
create table if not exists public.itens_a_cotar (
  id                  bigint generated always as identity primary key,
  descricao           text,
  descricao_norm      text,
  chave_grupo         text,
  pa                  text,
  origem              text,
  cliente             text,
  status              text default 'pendente',
  vezes               integer default 1,
  fornecedor_resposta text,
  preco_recebido      numeric,
  obs                 text,
  criado_em           timestamptz default now(),
  atualizado_em       timestamptz default now()
);

-- PEDIDOS_COMPRA (itens em JSON; UPDATE por id, nunca DELETE)
create table if not exists public.pedidos_compra (
  id               bigint generated always as identity primary key,
  numero_orcamento text,
  cliente          text,
  vendedora        text,
  status           text,
  itens            jsonb,
  total_compra     numeric,
  mkp_medio        numeric,
  created_at       timestamptz default now()
);

-- NOTAS (painel)
create table if not exists public.notas (
  id         bigint generated always as identity primary key,
  texto      text,
  feito      boolean default false,
  created_at timestamptz default now()
);

-- CMED_DICIONARIO (marca -> substancia/PA)
create table if not exists public.cmed_dicionario (
  id         bigint generated always as identity primary key,
  marca_norm text,
  substancia text,
  dose_norm  text,
  is_combo   boolean default false
);

-- COMISSOES: fora do pacote FPMED — tabelas comissoes_isadora/comissoes_externas
-- DROPADAS em 22/07/2026 (as telas que as usavam sairam do menu na mesma data).

-- VIEWS usadas pelo app
create or replace view public.v_compras_mensal as
  select cliente_codigo,
         to_char(data_compra,'YYYY-MM') as ano_mes,
         count(*)          as num_compras,
         sum(valor_total)  as total_mes
  from public.compras
  where data_compra is not null
  group by cliente_codigo, to_char(data_compra,'YYYY-MM');

-- v_preco_variacao: stub com as colunas certas (retorna vazio ate haver historico/logica real)
create or replace view public.v_preco_variacao as
  select null::text    as fornecedor,
         null::text    as produto_norm,
         null::numeric as var_pct,
         null::numeric as preco_atual,
         null::numeric as preco_anterior,
         null::date    as data_anterior
  where false;

-- PostgREST: recarregar o cache de schema (pegadinha do CONTINUAR)
notify pgrst, 'reload schema';
